const DUMMY_BUSINESSES = [
  {
    age: 3,
    askingPrice: 1000000,
    description:
      'Mussum Ipsum, cacilds vidis litro abertis. Sapien in monti palavris qui num significa nadis i pareci latim.Todo mundo vê os porris que eu tomo, mas ninguém vê os tombis que eu levo!Admodum accumsan disputationi eu sit. Vide electram sadipscing et per.Praesent vel viverra nisi. Mauris aliquet nunc non turpis scelerisque, eget.',
    id: '0001',
    imageUrl: 'https://neilpatel.com/wp-content/uploads/2018/10/blog.jpg',
    monthlyProfit: 8000,
    monthlyRevenue: 6000000,
    niche: 'Home & Garden',
    ownerId: 'MyTQBsoMezR509xgt2fUNe4FRsB3',
    title: 'Blog 1',
    type: 'Blog / Content',
  },
  {
    age: 3,
    askingPrice: 1000000,
    description:
      'Mussum Ipsum, cacilds vidis litro abertis. Sapien in monti palavris qui num significa nadis i pareci latim.Todo mundo vê os porris que eu tomo, mas ninguém vê os tombis que eu levo!Admodum accumsan disputationi eu sit. Vide electram sadipscing et per.Praesent vel viverra nisi. Mauris aliquet nunc non turpis scelerisque, eget.',
    id: '0002',
    imageUrl:
      'https://www.civitatis.com/f/hungria/budapest/galeria/parlamento-budapest.jpg',
    monthlyProfit: 80000,
    monthlyRevenue: 320000,
    niche: 'Hobbies',
    ownerId: 'D5rLcvZQu3dv3Zd61W1nNeaKyII2',
    title: 'Travel Blog',
    type: 'Blog / Content',
  },
  {
    age: 3,
    askingPrice: 832000,
    description:
      'This is a e-commerce created using Shopify, that has some own products, but also make upsells via dropshipping model',
    id: '0003',
    imageUrl:
      'https://printify.com/wp-content/uploads/2022/05/The-Best-Shopify-Store-Examples-for-2022.png',
    monthlyProfit: 11500,
    monthlyRevenue: 40000,
    niche: 'Fashion',
    ownerId: 'MyTQBsoMezR509xgt2fUNe4FRsB3',
    title: 'Store',
    type: 'E-Commerce',
  },
  {
    age: 3,
    askingPrice: 96000,
    description:
      'This is a e-commerce created using Shopify, that has some own products, but also make upsells via dropshipping model',
    id: '0004',
    imageUrl: 'https://media.graphassets.com/53cwIkkyTGCGg2faP1WY',
    monthlyProfit: 8000,
    monthlyRevenue: 40000,
    niche: 'Fashion',
    ownerId: 'D5rLcvZQu3dv3Zd61W1nNeaKyII2',
    title: 'Another Store',
    type: 'E-Commerce',
  },
  {
    age: 3,
    askingPrice: 96000,
    description:
      'This is a e-commerce created using Shopify, that has some own products, but also make upsells via dropshipping model',
    id: '0005',
    imageUrl:
      'https://res.cloudinary.com/webmaster-marke/image/upload/v1664999029/o-que-%C3%A9-digital-influencer.jpg',
    monthlyProfit: 8000,
    monthlyRevenue: 40000,
    niche: 'Fashion',
    ownerId: 'MyTQBsoMezR509xgt2fUNe4FRsB3',
    title: 'IG Profile',
    type: 'IG Profile',
  },
  {
    age: 3,
    askingPrice: 96000,
    description:
      'This is a e-commerce created using Shopify, that has some own products, but also make upsells via dropshipping model',
    id: '0006',
    imageUrl:
      'https://studiodamaart.com.br/wp-content/uploads/2022/08/photo-1592329347810-258afdd206bb.jpeg',
    monthlyProfit: 8000,
    monthlyRevenue: 40000,
    niche: 'Fashion',
    ownerId: 'D5rLcvZQu3dv3Zd61W1nNeaKyII2',
    title: 'Tik Tok Profile',
    type: 'Tik Tok Profile',
  },
  {
    age: 2,
    askingPrice: 30,
    description: 'to cansado de tik tok, passando pra quem gosta de cãrezinhos',
    id: '1690158683351',
    imageUrl:
      'https://img.freepik.com/vetores-gratis/hamburguer-realista-no-fundo-do-quadro_79603-1042.jpg?w=2000',
    monthlyProfit: 49999,
    monthlyRevenue: 50000,
    niche: 'Pet',
    ownerId: '9BeWrC1Wq7dcXYiOmgUC04lkWht2',
    title: 'TAG BURG',
    type: 'Tik Tok Profile',
  },
  {
    age: 1,
    askingPrice: 864000,
    description: 'This is a Dark Kitchen that runs in NY',
    id: '1690199585161',
    imageUrl:
      'https://media.istockphoto.com/id/477299443/pt/foto/rolo-de-m%C3%A3o.jpg?s=612x612&w=0&k=20&c=7kIDGpHGcOfaJuwQgTWw_mMDKEVD7EnSPfRYY3eh6C8=',
    monthlyProfit: 36000,
    monthlyRevenue: 180000,
    niche: 'Food',
    ownerId: 'd8mu3w7gDFZlPDsIG7Q6l5Rjr5w1',
    title: 'Japanese Dark Kitchen',
    type: 'E-Commerce',
  },
  {
    age: 3,
    askingPrice: 1500000,
    description: 'Pizzaria bem localizada',
    id: '1690310456154',
    imageUrl:
      'https://media-cdn.tripadvisor.com/media/photo-s/1a/f9/e2/8a/pizzaria-hermon.jpg',
    monthlyProfit: 99000,
    monthlyRevenue: 125000,
    niche: 'Food',
    ownerId: 'NTGAdCX9bLXHWSv9SkXnYO5DUhx1',
    title: 'Pizzaria Pizza Boa',
    type: 'Others',
  },
];

const DUMMY_USERS = [
  {
    country: 'Brasil',
    description: 'sou o LB',
    email: 'raphael.bm@hotmail.com.br',
    id: '9BeWrC1Wq7dcXYiOmgUC04lkWht2',
    imageUrl: 'https://www.thispersondoesnotexist.com/',
    linkedinUrl: 'linkedin.com',
    name: 'Lapael Barros',
    password: 'QPwo!)29',
  },
  {
    country: 'Brazil',
    description: 'qweasd',
    email: 'test2@gmail.com',
    id: 'D5rLcvZQu3dv3Zd61W1nNeaKyII2',
    imageUrl:
      'https://static.vecteezy.com/ti/fotos-gratis/p3/6671766-fantastica-lua-magica-luz-e-agua-barco-com-arvore-papel-de-parede-gratis-foto.jpg',
    linkedinUrl: 'asdf.com',
    name: 'Test Two',
    password: 'QPwo!)29',
  },
  {
    country: 'Brazil',
    description: 'qweasd',
    email: 'test4@gmail.com',
    id: 'F57HWSwL4zXiRBCHfBtg4Nwf4Mi2',
    imageUrl: 'https://www.thispersondoesnotexist.com/',
    linkedinUrl: 'asdf.com',
    name: 'Test Four',
    password: 'QPwo!)29',
  },
  {
    country: 'Brazil',
    description: 'I am the 5th test!',
    email: 'test6@gmail.com',
    id: 'FhLOTrsi46VRTTHOCC8Ndztbdck2',
    imageUrl: 'https://thispersondoesnotexist.com/',
    linkedinUrl: 'https://www.linkedin.com/in/rfayad/',
    name: 'Test Six',
    password: 'QPwo!)29',
  },
  {
    country: 'Brasil',
    description: '......',
    email: 'laismelo-q@outlook.com',
    id: 'IuVbpISBBmTgrHjCOGesD90430F2',
    imageUrl: 'https://thispersondoesnotexist.com/',
    linkedinUrl: 'https://www.linkedin.com/in/la%C3%ADs-de-melo-647ab3187',
    name: 'Lais de Melo',
    password: 'QPwo!)29',
  },
  {
    country: 'Brazil',
    description: 'qweasd',
    email: 'test9@gmail.com',
    id: 'KE1N4LYvG6R6WGJcvz2dcK0JtdQ2',
    imageUrl:
      'https://www.designerd.com.br/wp-content/uploads/2019/04/imagens-blogs-chamar-atencao-publico-fb.jpg',
    linkedinUrl: 'https://www.linkedin.com',
    name: 'test three',
    password: 'QPwo!)29',
  },
  {
    country: 'Brazil',
    description: 'Random Test',
    email: 'random@gmail.com',
    id: 'KharvziCLDe3pb3HJCffhW3saOE2',
    imageUrl: 'https://www.thispersondoesnotexist.com/',
    linkedinUrl: 'asdf.com',
    name: 'Random Person',
    password: 'QPwo!)29',
  },
  {
    country: 'Brazil',
    description: 'qweasd',
    email: 'test1@gmail.com',
    id: 'MyTQBsoMezR509xgt2fUNe4FRsB3',
    imageUrl:
      'https://media.licdn.com/dms/image/C4E03AQH5HDkBly2nqg/profile-displayphoto-shrink_400_400/0/1655491533997?e=1695859200&v=beta&t=TR4jA7GCVvRiII1fPW26BSvXNgaFqGDEvRYV-AHtQac',
    linkedinUrl: 'asdf.com',
    name: 'Test One',
    password: 'QPwo!)29',
  },
  {
    country: 'Brazil',
    description: 'Teste....',
    email: 'joaosilva123testeeee@hotmail.com',
    id: 'NTGAdCX9bLXHWSv9SkXnYO5DUhx1',
    imageUrl: 'https://thispersondoesnotexist.com/',
    linkedinUrl: 'www.linkedin.com',
    name: 'Joao da Silva Silva Silva',
    password: 'QPwo!)29',
  },
  {
    country: 'Noruega',
    description: 'Cantor profissional',
    email: 'bruno.mars@gmail.com',
    id: 'NoFOmn8Zj9NuergZFJp7nsYpeHY2',
    imageUrl: 'https://thispersondoesnotexist.com/',
    linkedinUrl: 'https://linkedin.com/bruno.mars',
    name: 'Bruno Mars',
    password: 'QPwo!)29',
  },
  {
    country: 'Inglaterra',
    description: 'SOu a Jéssica :)',
    email: 'jessica_nvp@hotmail.com',
    id: 'TNXglS34fBgjrllhIb04cpRadTo2',
    imageUrl:
      'https://media.licdn.com/dms/image/C4D03AQFHtp0UUwGkUg/profile-displayphoto-shrink_800_800/0/1628269322846?e=1695254400&v=beta&t=P382GGlj5wZ0wya2-gSF2UHJyUNSbPk40JXoMClxCzA',
    linkedinUrl: 'asdf.com',
    name: 'Jessica Nadalete',
    password: 'QPwo!)29',
  },
  {
    country: 'Brazil',
    description: 'I am the third tester :)',
    email: 'test3@gmail.com',
    id: 'd8mu3w7gDFZlPDsIG7Q6l5Rjr5w1',
    imageUrl: 'https://www.thispersondoesnotexist.com/',
    linkedinUrl: 'linkedin.com',
    name: 'Test Three',
    password: 'QPwo!)29',
  },
  {
    country: 'Brasil',
    description: 'Sou um profissional preparado pra isso ',
    email: 'arnol@shwazenegger.com',
    id: 'iPSquXQKf3Z1lW569J1AlVxX6Sk1',
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTBD2UhtwY8sAmED67RCQ3vnN-iNt5egaIXA&usqp=CAU',
    linkedinUrl: 'sandrinha.com',
    name: 'Arnold Shwarmanegger',
    password: 'QPwo!)29',
  },
  {
    country: 'Brazil',
    description: 'qweasd',
    email: 'testx@gmail.com',
    id: 'jSzK7ycXgCYxCEm2GMuuBrx7s5d2',
    imageUrl: 'https://www.thispersondoesnotexist.com/',
    linkedinUrl: 'linkedin.com',
    name: 'test x',
    password: 'QPwo!)29',
  },
  {
    country: 'Brasil',
    description: 'Eu sou a Jessica :)',
    email: 'jessica_nvp@hotmail.com',
    id: 'kw6B22qamwXkCISafkYbLtdRQKC2',
    imageUrl: 'https://thispersondoesnotexist.com/',
    linkedinUrl: 'blabla.com',
    name: 'Jessica Pedro',
    password: 'QPwo!)29',
  },
  {
    country: 'Brazil',
    description: 'Im a random new test',
    email: 'test5@gmail.com',
    id: 'qzRNrVmjIyVyUkoYrtri33D66Zy1',
    imageUrl: 'https://www.thispersondoesnotexist.com/',
    linkedinUrl: 'asdf.com',
    name: 'Test Five',
    password: 'QPwo!)29',
  },
];

const DUMMY_OFFERS = [
  {
    businessId: '0002',
    id: '1690503425231',
    message: 'qweasd',
    offerValue: 42000,
    sender: 'MyTQBsoMezR509xgt2fUNe4FRsB3',
    status: 'accepted',
  },
  {
    businessId: '0001',
    id: '1690503573243',
    message: 'qewaddaf',
    offerValue: 12,
    sender: 'D5rLcvZQu3dv3Zd61W1nNeaKyII2',
    status: 'accepted',
  },
  {
    businessId: '0002',
    id: '1690503663359',
    message: 'qwseasd',
    offerValue: 1,
    sender: 'MyTQBsoMezR509xgt2fUNe4FRsB3',
    status: 'accepted',
  },
  {
    businessId: '0004',
    id: '1690503685311',
    message: 'qweewqdsa',
    offerValue: 123,
    sender: 'MyTQBsoMezR509xgt2fUNe4FRsB3',
    status: 'accepted',
  },
  {
    businessId: '0002',
    id: '1690592018417',
    message: 'Testefff',
    offerValue: 66666666,
    sender: 'MyTQBsoMezR509xgt2fUNe4FRsB3',
    status: 'active',
  },
  {
    businessId: '0002',
    id: '1690638828967',
    message: 'Me interessei',
    offerValue: 10,
    sender: 'NoFOmn8Zj9NuergZFJp7nsYpeHY2',
    status: 'active',
  },
  {
    businessId: '0001',
    id: '1692132751533',
    message: 'qweasd',
    offerValue: 35,
    sender: 'KE1N4LYvG6R6WGJcvz2dcK0JtdQ2',
    status: 'accepted',
  },
];

exports.businesses = DUMMY_BUSINESSES;
exports.users = DUMMY_USERS;
exports.offers = DUMMY_OFFERS;
